### ISSUE TITLE
Configure the application

### ISSUE THREAD

**Issue by alex6ripetti** [chargag/oxygen-cs-grp1-eq8#7]
**Is your feature request related to a problem? Please describe.**
We need to configure the application with environment variables. The solution needs to have tests.

**Describe the solution you'd like**
We want a file that contains the environment variable to configure the application.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
If a environment variable is not defined, we need to set a default value. If the token is not set we need to return an error. For each modification in the code we need to add unit tests.

**Comment by chargag** [comment]
This needs clarification @alex6ripetti, we already have an env file. Which variables should be used and tested?

**Comment by alex6ripetti** [comment]
Be careful, this new env file will be in the oxygen application. We need to set those variables : 
- HOST: The host of the sensor hub and HVAC system.
- TOKEN: The token for authenticating requests.
- TICKETS: The number of tickets.
- T_MAX: The maximum allowed temperature.
- T_MIN: The minimum allowed temperature.
- DATABASE: The database connection details.
